# Generated by Django 3.1.3 on 2020-12-06 03:56

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('driver', models.CharField(max_length=20)),
                ('trip_no', models.IntegerField()),
                ('phone', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_licence', models.CharField(max_length=200, unique=True)),
                ('licence_issued_date', models.DateTimeField(verbose_name='issued date')),
                ('reg_date', models.DateTimeField(default=datetime.datetime(2020, 12, 5, 19, 56, 53, 628618), verbose_name='date registerd')),
            ],
        ),
        migrations.CreateModel(
            name='machine_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200)),
                ('machineID', models.CharField(max_length=200)),
                ('reg_date', models.DateTimeField(default=datetime.datetime(2020, 12, 5, 19, 56, 53, 634718), verbose_name='date registerd')),
            ],
        ),
        migrations.CreateModel(
            name='penalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_type', models.CharField(max_length=200)),
                ('vehicle_plate', models.CharField(max_length=200)),
                ('reg_date', models.DateTimeField(default=datetime.datetime(2020, 12, 5, 19, 56, 53, 631699), verbose_name='date registerd')),
                ('trip_no', models.IntegerField(null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('reg_date', models.DateTimeField(default=datetime.datetime(2020, 12, 5, 19, 56, 53, 627382), verbose_name='date registerd')),
            ],
        ),
        migrations.CreateModel(
            name='route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_type', models.CharField(default='normal', max_length=200)),
                ('length', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('reg_date', models.DateTimeField(default=datetime.datetime(2020, 12, 5, 19, 56, 53, 635676), verbose_name='date registerd')),
            ],
        ),
        migrations.CreateModel(
            name='RouteTypes',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 12, 5, 19, 56, 53, 635676))),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'route_types',
            },
        ),
        migrations.CreateModel(
            name='subcity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcity_name', models.CharField(max_length=200)),
                ('Number_Of_Station', models.PositiveIntegerField()),
                ('Number_Of_Machine', models.PositiveIntegerField()),
                ('Number_Of_Root', models.PositiveIntegerField()),
                ('Number_Of_Vehicles', models.PositiveIntegerField()),
                ('reg_date', models.DateTimeField(default=datetime.datetime(2020, 12, 5, 19, 56, 53, 629814), verbose_name='date registerd')),
            ],
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=200)),
                ('plate_no', models.CharField(max_length=200, unique=True)),
                ('model', models.CharField(max_length=200)),
                ('vehicle_size', models.PositiveSmallIntegerField()),
                ('reg_date', models.DateTimeField(default=datetime.datetime(2020, 12, 5, 19, 56, 53, 630410), verbose_name='date registerd')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityadmin.driver')),
                ('subcity', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cityadmin.subcity')),
            ],
        ),
        migrations.CreateModel(
            name='waiting_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coming_time', models.DateTimeField(verbose_name='coming_time')),
                ('going_time', models.DateTimeField(verbose_name='going_time')),
                ('reg_date', models.DateTimeField(default=datetime.datetime(2020, 12, 5, 19, 56, 53, 637886), verbose_name='date registerd')),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityadmin.route')),
            ],
        ),
        migrations.CreateModel(
            name='vehicles_location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('reg_date', models.DateTimeField(default=datetime.datetime(2020, 12, 5, 19, 56, 53, 637886), verbose_name='date registerd')),
                ('device_id', models.CharField(max_length=200)),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityadmin.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=200)),
                ('Number_Of_Root', models.PositiveIntegerField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('reg_date', models.DateTimeField(default=datetime.datetime(2020, 12, 5, 19, 56, 53, 632927), verbose_name='date registerd')),
                ('subcity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityadmin.subcity')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest', to='cityadmin.station'),
        ),
        migrations.AddField(
            model_name='route',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='cityadmin.station'),
        ),
        migrations.CreateModel(
            name='machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=200, unique=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('reg_date', models.DateTimeField(default=datetime.datetime(2020, 12, 5, 19, 56, 53, 634130), verbose_name='date registerd')),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityadmin.station')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityadmin.profile'),
        ),
        migrations.CreateModel(
            name='deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounde', models.PositiveIntegerField()),
                ('route_type', models.CharField(max_length=20, null=True)),
                ('route_length', models.CharField(max_length=200, null=True)),
                ('route_price', models.FloatField(null=True)),
                ('source_name', models.CharField(max_length=200, null=True)),
                ('deestination_name', models.CharField(max_length=200, null=True)),
                ('reg_date', models.DateTimeField(default=datetime.datetime(2020, 12, 5, 19, 56, 53, 636751), verbose_name='date registerd')),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityadmin.route')),
                ('vehicle_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityadmin.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='assign_vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('assign_date', models.DateTimeField(default=datetime.datetime(2020, 12, 5, 19, 56, 53, 638668), verbose_name='date assigned')),
                ('status', models.CharField(default='pending', max_length=200)),
                ('vehicles_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityadmin.vehicle')),
            ],
        ),
    ]
