# Generated by Django 3.1.3 on 2020-11-21 04:55

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_licence', models.CharField(max_length=200, unique=True)),
                ('licence_issued_date', models.DateTimeField(verbose_name='issued date')),
                ('reg_date', models.DateTimeField(verbose_name='date registerd')),
            ],
        ),
        migrations.CreateModel(
            name='machine_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200)),
                ('machineID', models.CharField(max_length=200)),
                ('reg_date', models.DateTimeField(verbose_name='date registerd')),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('reg_date', models.DateTimeField(verbose_name='date registerd')),
            ],
        ),
        migrations.CreateModel(
            name='rails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid_rail_d', models.IntegerField()),
                ('f_code_des', models.CharField(max_length=254)),
                ('exs_descri', models.CharField(max_length=254)),
                ('fco_descri', models.CharField(max_length=254)),
                ('fid_countr', models.IntegerField()),
                ('iso', models.CharField(max_length=7)),
                ('isocountry', models.CharField(max_length=54)),
            ],
        ),
        migrations.CreateModel(
            name='route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_type', models.CharField(max_length=200)),
                ('length', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('reg_date', models.DateTimeField(verbose_name='date registerd')),
            ],
        ),
        migrations.CreateModel(
            name='RouteTypes',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'route_types',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='subcity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcity_name', models.CharField(max_length=200)),
                ('Number_Of_Station', models.PositiveIntegerField()),
                ('Number_Of_Machine', models.PositiveIntegerField()),
                ('Number_Of_Root', models.PositiveIntegerField()),
                ('Number_Of_Vehicles', models.PositiveIntegerField()),
                ('reg_date', models.DateTimeField(verbose_name='date registerd')),
            ],
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=200)),
                ('plate_no', models.CharField(max_length=200, unique=True)),
                ('model', models.CharField(max_length=200)),
                ('vehicle_size', models.PositiveSmallIntegerField()),
                ('reg_date', models.DateTimeField(verbose_name='date registerd')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.driver')),
                ('subcity', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.subcity')),
            ],
        ),
        migrations.CreateModel(
            name='WorldBorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('area', models.IntegerField()),
                ('pop2005', models.IntegerField(verbose_name='Population 2005')),
                ('fips', models.CharField(max_length=2, null=True, verbose_name='FIPS Code')),
                ('iso2', models.CharField(max_length=2, verbose_name='2 Digit ISO')),
                ('iso3', models.CharField(max_length=3, verbose_name='3 Digit ISO')),
                ('un', models.IntegerField(verbose_name='United Nations Code')),
                ('region', models.IntegerField(verbose_name='Region Code')),
                ('subregion', models.IntegerField(verbose_name='Sub-Region Code')),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='waiting_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coming_time', models.DateTimeField(verbose_name='coming_time')),
                ('going_time', models.DateTimeField(verbose_name='going_time')),
                ('reg_date', models.DateTimeField(verbose_name='date registerd')),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.route')),
            ],
        ),
        migrations.CreateModel(
            name='vehicles_location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('reg_date', models.DateTimeField(verbose_name='date registerd')),
                ('device_id', models.CharField(max_length=200)),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=200)),
                ('Number_Of_Root', models.PositiveIntegerField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('reg_date', models.DateTimeField(verbose_name='date registerd')),
                ('subcity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.subcity')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest', to='myapp.station'),
        ),
        migrations.AddField(
            model_name='route',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='myapp.station'),
        ),
        migrations.CreateModel(
            name='penalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_type', models.CharField(max_length=200)),
                ('reg_date', models.DateTimeField(verbose_name='date registerd')),
                ('driver_licence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.driver')),
                ('vehicle_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=200, unique=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('reg_date', models.DateTimeField(verbose_name='date registerd')),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.station')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.profile'),
        ),
        migrations.CreateModel(
            name='deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounde', models.PositiveIntegerField()),
                ('reg_date', models.DateTimeField(verbose_name='date registerd')),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.route')),
                ('vehicle_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='assign_vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_date', models.DateTimeField(default=datetime.datetime(2020, 11, 20, 20, 55, 46, 963774), verbose_name='date assigned')),
                ('status', models.CharField(default='pending', max_length=200)),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.route')),
                ('vehicles_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vehicle')),
            ],
        ),
    ]
