# Generated by Django 3.0.3 on 2020-02-29 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lattitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('altitude', models.CharField(max_length=200)),
                ('reg_date', models.DateTimeField(verbose_name='date registerd')),
            ],
        ),
        migrations.CreateModel(
            name='machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=200, unique=True)),
                ('reg_date', models.DateTimeField(verbose_name='date registerd')),
            ],
        ),
        migrations.CreateModel(
            name='route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_type', models.CharField(max_length=200)),
                ('length', models.CharField(max_length=200)),
                ('reg_date', models.DateTimeField(verbose_name='date registerd')),
            ],
        ),
        migrations.CreateModel(
            name='station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=200)),
                ('reg_date', models.DateTimeField(verbose_name='date registerd')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.location')),
            ],
        ),
        migrations.CreateModel(
            name='subcity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcity_name', models.CharField(max_length=200)),
                ('reg_date', models.DateTimeField(verbose_name='date registerd')),
            ],
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=200)),
                ('plate_no', models.CharField(max_length=200, unique=True)),
                ('model', models.CharField(max_length=200, unique=True)),
                ('vehicle_size', models.PositiveSmallIntegerField()),
                ('reg_date', models.DateTimeField(verbose_name='date registerd')),
            ],
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_licence',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='waiting_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coming_time', models.DateTimeField(verbose_name='coming_time')),
                ('going_time', models.DateTimeField(verbose_name='going_time')),
                ('reg_date', models.DateTimeField(verbose_name='date registerd')),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.machine')),
            ],
        ),
        migrations.CreateModel(
            name='vehicle_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(verbose_name='date requested')),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.machine')),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.route')),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.station')),
                ('subcity_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.subcity')),
            ],
        ),
        migrations.AddField(
            model_name='station',
            name='subcity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.subcity'),
        ),
        migrations.AddField(
            model_name='route',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.station'),
        ),
        migrations.CreateModel(
            name='penalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_type', models.CharField(max_length=200)),
                ('reg_date', models.DateTimeField(verbose_name='date registerd')),
                ('driver_licence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.driver')),
                ('vehicle_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='station_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.station'),
        ),
        migrations.CreateModel(
            name='deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(verbose_name='date registerd')),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.route')),
                ('vehicle_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='assign_vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_date', models.DateTimeField(verbose_name='date assigned')),
                ('driver_licence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.driver')),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.route')),
                ('vehicle_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vehicle')),
            ],
        ),
    ]
