# Generated by Django 3.0.3 on 2020-03-10 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200229_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dest', to='myapp.station'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='myapp.station'),
        ),
    ]
