# Generated by Django 3.1.3 on 2020-11-26 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20201126_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('driver', models.CharField(max_length=20)),
                ('trip_no', models.IntegerField()),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
        migrations.AlterField(
            model_name='assign_vehicle',
            name='assign_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 10, 52, 7, 246046), verbose_name='date assigned'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 10, 52, 7, 245049), verbose_name='date registerd'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 10, 52, 7, 240064), verbose_name='date registerd'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 10, 52, 7, 243122), verbose_name='date registerd'),
        ),
        migrations.AlterField(
            model_name='machine_data',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 10, 52, 7, 243122), verbose_name='date registerd'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 10, 52, 7, 239064), verbose_name='date registerd'),
        ),
        migrations.AlterField(
            model_name='route',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 10, 52, 7, 244051), verbose_name='date registerd'),
        ),
        migrations.AlterField(
            model_name='routetypes',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 10, 52, 7, 244051)),
        ),
        migrations.AlterField(
            model_name='station',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 10, 52, 7, 242058), verbose_name='date registerd'),
        ),
        migrations.AlterField(
            model_name='subcity',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 10, 52, 7, 241158), verbose_name='date registerd'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 10, 52, 7, 241158), verbose_name='date registerd'),
        ),
        migrations.AlterField(
            model_name='vehicles_location',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 10, 52, 7, 246046), verbose_name='date registerd'),
        ),
        migrations.AlterField(
            model_name='waiting_time',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 10, 52, 7, 245049), verbose_name='date registerd'),
        ),
    ]
