# Generated by Django 3.1.3 on 2020-11-28 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20201128_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='deestination_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='route_length',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='route_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='route_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='source_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='assign_vehicle',
            name='assign_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 10, 12, 40, 999812), verbose_name='date assigned'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 10, 12, 40, 998815), verbose_name='date registerd'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 10, 12, 40, 993828), verbose_name='date registerd'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 10, 12, 40, 996820), verbose_name='date registerd'),
        ),
        migrations.AlterField(
            model_name='machine_data',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 10, 12, 40, 996820), verbose_name='date registerd'),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 10, 12, 40, 995822), verbose_name='date registerd'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 10, 12, 40, 992830), verbose_name='date registerd'),
        ),
        migrations.AlterField(
            model_name='route',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 10, 12, 40, 997817), verbose_name='date registerd'),
        ),
        migrations.AlterField(
            model_name='routetypes',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 10, 12, 40, 997817)),
        ),
        migrations.AlterField(
            model_name='station',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 10, 12, 40, 995822), verbose_name='date registerd'),
        ),
        migrations.AlterField(
            model_name='subcity',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 10, 12, 40, 994825), verbose_name='date registerd'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 10, 12, 40, 994825), verbose_name='date registerd'),
        ),
        migrations.AlterField(
            model_name='vehicles_location',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 10, 12, 40, 999812), verbose_name='date registerd'),
        ),
        migrations.AlterField(
            model_name='waiting_time',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 10, 12, 40, 998815), verbose_name='date registerd'),
        ),
    ]
