# Generated by Django 3.0.3 on 2020-02-29 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_licence', models.CharField(max_length=200)),
                ('licence_issued_date', models.DateTimeField(verbose_name='issued date')),
                ('reg_date', models.DateTimeField(verbose_name='date registerd')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.profile')),
            ],
        ),
    ]
