# Generated by Django 3.0.3 on 2020-02-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Roll',
            field=models.CharField(choices=[('superAdmin', 'superAdmin'), ('cityAdmin', 'cityAdmin'), ('subcityAdmin', 'subcityAdmin'), ('cityStaff', 'cityStaff'), ('subcityStaff', 'subcityStaff')], max_length=20),
        ),
    ]
